/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework3;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void test() {
        ArrTransformFromEvenToOddByArrs objectOfAnotherClass = new ArrTransformFromEvenToOddByArrs();
        objectOfAnotherClass.transfortOfAray();
        //
    }
}
